# -*- coding: utf-8 -*-
"""SA_augementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12tPFUgUQX8dHVrzl-RdcEuaTgqaJIv3y
"""

import pandas as pd
from transformers import pipeline
from tqdm import tqdm

generator = pipeline(
    "text-generation",
    model="meta-llama/Llama-3.2-8B-Instruct",
    device_map="auto"
)

def augment_tweet(tweet, location, created_at, event="2018 California Wildfire"):
    prompt = f"""
You are provided with the following information from a Situational Awareness (SA) dataset related to {event}:

- Tweet text: "{tweet}"
- Location: "{location}"
- Created at: "{created_at}"

Your task is to enrich and complete the Tweet text by:
1. Use the created_at field to add or refine timestamps, date ranges, and possible event progression details.
2. Use the location field to add more specific spatial details (e.g., city, county, region, GPS coordinates, or descriptive locations).
If the location is missing or vague, infer the most plausible one consistent with the event context.
3. Ensure the original intent and content of the tweet is preserved, while filling in gaps with logical, consistent details.
4. All augmented information must align with the broader context of the event. If exact details are unavailable, provide the most reasonable approximation.

Output ONLY the augmented tweet text and do not include any explanations or additional text.
"""
    response = generator(prompt, max_new_tokens=200, temperature=0.7, do_sample=True)
    return response[0]["generated_text"].strip()

df = pd.read_csv("SA_final.csv")

augmented_tweets = []
for _, row in tqdm(df.iterrows(), total=len(df)):
    tweet = str(row.get("text", ""))
    location = str(row.get("place", ""))
    created_at = str(row.get("created_at", ""))
    augmented_text = augment_tweet(tweet, location, created_at)
    augmented_tweets.append(augmented_text)

df["augmented_text_0"] = augmented_tweets
df.to_csv("SA_augmented_tweets_2.csv", index=False)