# -*- coding: utf-8 -*-
"""CN_jittered.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17E6_mYHlwWNO_1wzM9x75VJSMPCNBoUo
"""

import pandas as pd
import numpy as np

"""# Add new_lat, new_lon, new_created_at columns in Colab

"""

# Add new_lat, new_lon, new_created_at columns in Colab
import math, random
from datetime import timedelta, datetime, timezone
import pandas as pd
import numpy as np

# === Config thresholds ===
NEED_THRESHOLDS = {
   # "medical_emergency": {"urgency_hours": 12, "radius_km": 10},
    "medical_help": {"urgency_hours": 12, "radius_km": 10},
    "search_and_rescue": {"urgency_hours": 24, "radius_km": 20},
    "protection": {"urgency_hours": 48, "radius_km": 30},
    "food_water": {"urgency_hours": 48, "radius_km": 30},
    "shelter": {"urgency_hours": 120, "radius_km": 80},
    "logistics": {"urgency_hours": 72, "radius_km": 50},
    "transportation": {"urgency_hours": 72, "radius_km": 50},
    "power_restoration": {"urgency_hours": 120, "radius_km": 80},
    "resource_coordination": {"urgency_hours": 72, "radius_km": 50},
    "family_reunification": {"urgency_hours": 72, "radius_km": 50},
}

EARTH_RADIUS_KM = 6371.0088
TW_TIME_FMT = "%a %b %d %H:%M:%S %z %Y"   # Twitter format

def parse_created_at(s: str) -> datetime:
    try:
        return datetime.strptime(s, TW_TIME_FMT)
    except ValueError:
        dt = datetime.strptime(s, "%a %b %d %H:%M:%S %Y")
        return dt.replace(tzinfo=timezone.utc)

def format_created_at(dt: datetime) -> str:
    return dt.strftime(TW_TIME_FMT)

def jitter_point(lat_deg, lon_deg, max_radius_km):
    if pd.isna(lat_deg) or pd.isna(lon_deg) or max_radius_km <= 0:
        return (np.nan, np.nan)

    distance_km = random.random() * max_radius_km
    bearing = random.random() * 2.0 * math.pi

    lat1, lon1 = math.radians(lat_deg), math.radians(lon_deg)
    ang_dist = distance_km / EARTH_RADIUS_KM

    sin_lat2 = math.sin(lat1) * math.cos(ang_dist) + math.cos(lat1) * math.sin(ang_dist) * math.cos(bearing)
    lat2 = math.asin(sin_lat2)

    lon2 = lon1 + math.atan2(
        math.sin(bearing) * math.sin(ang_dist) * math.cos(lat1),
        math.cos(ang_dist) - math.sin(lat1) * sin_lat2
    )

    lon2 = (lon2 + 3*math.pi) % (2*math.pi) - math.pi
    return math.degrees(lat2), math.degrees(lon2)

def jitter_time(created_at_str, max_hours):
    if not created_at_str or pd.isna(created_at_str) or max_hours <= 0:
        return created_at_str
    base = parse_created_at(created_at_str)
    hours = random.uniform(1e-6, max_hours)
    return format_created_at(base + timedelta(hours=hours))

def apply_jitter(df, seed=42):
    random.seed(seed); np.random.seed(seed)
    new_lat, new_lon, new_time = [], [], []
    for _, row in df.iterrows():
        need = row.get("need_type")
        th = NEED_THRESHOLDS.get(str(need).strip()) if pd.notna(need) else None
        if th:
            lat, lon = float(row["lat"]), float(row["lon"])
            nlat, nlon = jitter_point(lat, lon, th["radius_km"])
            ntime = jitter_time(row["created_at"], th["urgency_hours"])
        else:
            nlat, nlon, ntime = np.nan, np.nan, row["created_at"]
        new_lat.append(nlat); new_lon.append(nlon); new_time.append(ntime)
    df["new_lat"] = new_lat
    df["new_lon"] = new_lon
    df["new_created_at"] = new_time
    return df

from google.colab import files


# 2. Load CSV
df = pd.read_csv("CN_generated_704_columns_seperated.csv")

# 3. Apply jitter
df_out = apply_jitter(df)

# 4. Save và download
out_path = "CN_generated_704_jittered.csv"
df_out.to_csv(out_path, index=False)

df_final = pd.read_csv('CN_generated_704_jittered.csv')

df_final.columns

rename_map = {
    "augmented_text_0": "SA_enriched",
    "augmented_text_2": "ALL_CN_generated",
    "tweet": "CN_text",
    "augmented_text_CN": "CN_generated",
}
df_final = df_final.rename(columns=rename_map)

df_final.to_csv('CN_generated_jittered_renamed.csv', index=False)